metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - load
    - filesystem
    - fsstat
    - memory
    - network
    - process
  enabled: true
  period: 10s
  processes: ['.*']
output.elasticsearch:
{% set eshosts = salt['mine.get']('G@appname:metricsdb and G@roles:elasticsearch', 'network.ip_addrs', 'compound') %}
  hosts: [ "{{ eshosts|join('", "') }}:9200" ]
  protocol: "http"
  username: "{{ username }}"
  password: "{{ password }}"
